apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  labels:
    app: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: elasticsearch-pv
  resources:
    requests:
      storage: 50Gi
